version: '3.8'

services:
  lec-chatserver:
    image: narutosimaha/lec-chatserver
    user: "ejabberd:"
    # command: ["/bin/sh", "-c", "/home/ejabberd/conf/script.sh"]
    environment: 
      - JWT_KEY=secret
      - DB_TYPE=pgsql
      - DB_SERVER=langchat-db
      - DB_PORT=5432
      - DB_NAME=langchat
      - DB_USER=langteam
      - DB_PASSWORD=Aa1234
      - EJABBERD_HOST=localhost
    ports:
      - "5222:5222"
      - "5269:5269"
      - "5280:5280"
      - "5281:443"
    depends_on:
      langchat-db:
        condition: service_healthy  

  langchat-db:
    image: postgres:15.2
    environment:
      - POSTGRES_DB=langchat
      - POSTGRES_USER=langteam
      - POSTGRES_PASSWORD=Aa1234
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "langchat", "-U", "langteam" ]
      interval: 10s
      timeout: 5s
      retries: 5

  langchat-flyway:
    image: narutosimaha/flyway-langchat
    # command: -url=jdbc:postgresql://postgres:5432/ejabberd -user=ejabberd -password=ejabberd_password -connectRetries=60 migrate
    environment:
      - DATABASE_NAME=langchat
      - DATABASE_URL=jdbc:postgresql://langchat-db:5432
      - POSTGRES_USER=langteam
      - POSTGRES_PASSWORD=Aa1234
    # volumes:
    #   - ./lec-db/langchat/sql:/flyway/sql
    depends_on:
      - langchat-db

  langgeneral-db:
    image: postgres:15.2
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_DB=langgeneral
      - POSTGRES_USER=langteam
      - POSTGRES_PASSWORD=Aa1234
    ports:
      - 5434:5432
    volumes:
      - pgdata1:/var/lib/postgresql/data
    restart: always
    # healthcheck:
    #   test: [ "CMD", "pg_isready", "-q", "-d", "langchat", "-U", "langteam" ]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

      
  langgeneral-flyway:
    image: narutosimaha/flyway-langgeneral
    # command: -url=jdbc:postgresql://postgres:5432/ejabberd -user=ejabberd -password=ejabberd_password -connectRetries=60 migrate
    environment:
      - DATABASE_NAME=langgeneral
      - DATABASE_URL=jdbc:postgresql://langgeneral-db:5432
      - POSTGRES_USER=langteam
      - POSTGRES_PASSWORD=Aa1234
    # volumes:
    #   - ./lec-db/langchat/sql:/flyway/sql
    depends_on:
      - langgeneral-db
  

  lec-web:
    image: narutosimaha/lec-web
    # command: ["/bin/sh", "-c", "nginx-debug -g 'daemon off;'"]
    command: nginx-debug -g 'daemon off;'
    environment: 
      - NGINX_HOST=localhost
      - CHAT_WS_ENDPOINT=xmpp
      - CHAT_PORT=80
      - CHAT_HOST=lec-chathelper
      - CHAT_ENDPOINT=app
      - CHAT_SERVER_ENDPOINT=chat/xmpp/ws
    ports:
      - "80:80"
      - "443:443"


  lec-chathelper:
    image: narutosimaha/lec-chathelper-1
    command: /bin/sh -c "service celeryd start && httpd -D FOREGROUND"
    depends_on:
      - celery-broker
    environment: 
      - CREDENTIALS_KEY=secret
      - HOST=localhost
      - LANGGENERAL_DB_HOST=langgeneral-db
      - LANGGENERAL_PASS=Aa1234
      - LANGGENERAL_DB=langgeneral
      - LANGGENERAL_USER=langteam
      - LANGGENERAL_PORT=5432
      - LANGCHAT_DB=langchat
      - LANGCHAT_DB_HOST=langchat-db
      - LANGCHAT_PASS=Aa1234
      - LANGCHAT_USER=langteam
      - LANGCHAT_PORT=5432
      - TZ=Asia/Ho_Chi_Minh
      - TOKEN_DB_KEY=BCulJ35SlqRnAuxt
      - IV=EF3XDDnCjMpTJ8Pc
      - DJANGO_SECRET_KEY=Ref22pTceiaGogZFA732HXR4xPdtDtKmPs6hzXkNCa4mjWgYzx
      - OLD_SECRET_KEY=Ref22pTceiaGogZFA732HXR4xPdtDtKmPs6hzXkNCa4mjWgYzx
      - LANGCHAT_HOST=localhost
      - S3_ACCESS_KEY=AKIA5RKKGIJLRSD5GHDX
      - S3_SECRET_KEY=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
      - S3_BUCKET=language-exchanged
      - XMPP_UPLOAD_KEY=YOqe6JUVReE/iBJPDgSe25JYjD6vnz7b1Y7cRwRB
      - WEB_SERVER_HOST=lec-chathelper
      - APP_BROKERS=kafka:9092
      - CELERY_RESULT_BACKEND=redis://celery-broker:6379/0
      - CELERY_BROKER_URL=redis://celery-broker:6379/1
      - XMPP_WS_PORT=5280
      - XMPP_WS_HOST=lec-chatserver
      - LOG_FILE_FROM_ROOT=chat/chatworker/logs/worker.log
    ports:
      - "8082:80"

    
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000


  # Topics
  #   1. Personal info update.
  #   2. Friend relationship update: friend and unfriend.
  kafka:
    image: confluentinc/cp-kafka:7.3.2
    ports:
    # To learn about configuring Kafka for access across networks see
    # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  
  init-kafka:
    image: confluentinc/cp-kafka:7.3.2
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server broker:29092 --list

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server broker:29092 --create --if-not-exists --topic chathelper-friendstate --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server broker:29092 --create --if-not-exists --topic chathelper-userupdate --replication-factor 1 --partitions 1

      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server broker:29092 --list
      "
  celery-broker:
    image: redis
    ports:
      - "6379:6379"

  lec-chatfront:
    image: narutosimaha/lec-chatfront
    ports:
      - "8043:443"
    environment:
      - NGINX_HOST=localhost
volumes:
  pgdata:
  pgdata1: